// Code generated by make shadowspec-export; DO NOT EDIT.
// Source: pipeline/pkg/shadowspec

type DependencyKind = {
  type: string
  aliases?: string[]
  defaultImage: string
  defaultPort: number
  suggestedEnvVar: string
  label: string
}

type InputDriver = {
  driver: string
  label: string
  needsPort: boolean
  needsAmqp: boolean
}

export type ShadowCatalog = {
  dependencies: DependencyKind[]
  inputs: InputDriver[]
}

export const shadowCatalog: ShadowCatalog = {
  "dependencies": [
    {
      "type": "rabbitmq",
      "defaultImage": "rabbitmq:3-management-alpine",
      "defaultPort": 5672,
      "suggestedEnvVar": "AMQP_URL",
      "label": "RabbitMQ"
    },
    {
      "type": "mongodb",
      "aliases": [
        "mongo"
      ],
      "defaultImage": "mongo:6.0",
      "defaultPort": 27017,
      "suggestedEnvVar": "MONGO_URL",
      "label": "MongoDB"
    },
    {
      "type": "redis",
      "defaultImage": "redis:7-alpine",
      "defaultPort": 6379,
      "suggestedEnvVar": "REDIS_ADDR",
      "label": "Redis"
    },
    {
      "type": "postgres",
      "aliases": [
        "postgresql"
      ],
      "defaultImage": "postgres:16-alpine",
      "defaultPort": 5432,
      "suggestedEnvVar": "PG_DSN",
      "label": "PostgreSQL"
    }
  ],
  "inputs": [
    {
      "driver": "http_request",
      "label": "HTTP request",
      "needsPort": true,
      "needsAmqp": false
    },
    {
      "driver": "rabbitmq_message",
      "label": "RabbitMQ message",
      "needsPort": false,
      "needsAmqp": true
    }
  ]
} as const
