// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: monarch.proto

package monarchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase mirrors ShadowTest.status.phase. Deleting is written to the CR while
// teardown runs; Deleted is a stream-only tombstone after finalizers drop —
// the CR is gone by then, so consumers must treat it as "remove from cache".
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_PROGRESSING Phase = 1
	Phase_PHASE_READY       Phase = 2
	Phase_PHASE_FAILED      Phase = 3
	Phase_PHASE_DELETING    Phase = 4
	Phase_PHASE_DELETED     Phase = 5
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_PROGRESSING",
		2: "PHASE_READY",
		3: "PHASE_FAILED",
		4: "PHASE_DELETING",
		5: "PHASE_DELETED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_PROGRESSING": 1,
		"PHASE_READY":       2,
		"PHASE_FAILED":      3,
		"PHASE_DELETING":    4,
		"PHASE_DELETED":     5,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_monarch_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_monarch_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{0}
}

// BootStep mirrors ShadowTest.status.bootStep. Record and replay walk disjoint
// sub-paths, so consumers must not assume every step occurs.
type BootStep int32

const (
	BootStep_BOOT_STEP_UNSPECIFIED           BootStep = 0
	BootStep_BOOT_STEP_VALIDATING_INPUTS     BootStep = 1
	BootStep_BOOT_STEP_PROVISIONING_SINKS    BootStep = 2
	BootStep_BOOT_STEP_ACTIVATING_EGRESS_TAP BootStep = 3
	BootStep_BOOT_STEP_BINDING_AMQP          BootStep = 4
	BootStep_BOOT_STEP_PROVISIONING_SHADOW   BootStep = 5
	BootStep_BOOT_STEP_READY                 BootStep = 6
	BootStep_BOOT_STEP_FAILED                BootStep = 7
)

// Enum value maps for BootStep.
var (
	BootStep_name = map[int32]string{
		0: "BOOT_STEP_UNSPECIFIED",
		1: "BOOT_STEP_VALIDATING_INPUTS",
		2: "BOOT_STEP_PROVISIONING_SINKS",
		3: "BOOT_STEP_ACTIVATING_EGRESS_TAP",
		4: "BOOT_STEP_BINDING_AMQP",
		5: "BOOT_STEP_PROVISIONING_SHADOW",
		6: "BOOT_STEP_READY",
		7: "BOOT_STEP_FAILED",
	}
	BootStep_value = map[string]int32{
		"BOOT_STEP_UNSPECIFIED":           0,
		"BOOT_STEP_VALIDATING_INPUTS":     1,
		"BOOT_STEP_PROVISIONING_SINKS":    2,
		"BOOT_STEP_ACTIVATING_EGRESS_TAP": 3,
		"BOOT_STEP_BINDING_AMQP":          4,
		"BOOT_STEP_PROVISIONING_SHADOW":   5,
		"BOOT_STEP_READY":                 6,
		"BOOT_STEP_FAILED":                7,
	}
)

func (x BootStep) Enum() *BootStep {
	p := new(BootStep)
	*p = x
	return p
}

func (x BootStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BootStep) Descriptor() protoreflect.EnumDescriptor {
	return file_monarch_proto_enumTypes[1].Descriptor()
}

func (BootStep) Type() protoreflect.EnumType {
	return &file_monarch_proto_enumTypes[1]
}

func (x BootStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BootStep.Descriptor instead.
func (BootStep) EnumDescriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{1}
}

// CapturePhase mirrors ShadowTest.status.kaiselPhase. Distinguishes a degraded
// eBPF tap from one that is simply switched off in replay mode.
type CapturePhase int32

const (
	CapturePhase_CAPTURE_PHASE_UNSPECIFIED CapturePhase = 0
	CapturePhase_CAPTURE_PHASE_READY       CapturePhase = 1
	CapturePhase_CAPTURE_PHASE_DEGRADED    CapturePhase = 2
	CapturePhase_CAPTURE_PHASE_DISABLED    CapturePhase = 3
)

// Enum value maps for CapturePhase.
var (
	CapturePhase_name = map[int32]string{
		0: "CAPTURE_PHASE_UNSPECIFIED",
		1: "CAPTURE_PHASE_READY",
		2: "CAPTURE_PHASE_DEGRADED",
		3: "CAPTURE_PHASE_DISABLED",
	}
	CapturePhase_value = map[string]int32{
		"CAPTURE_PHASE_UNSPECIFIED": 0,
		"CAPTURE_PHASE_READY":       1,
		"CAPTURE_PHASE_DEGRADED":    2,
		"CAPTURE_PHASE_DISABLED":    3,
	}
)

func (x CapturePhase) Enum() *CapturePhase {
	p := new(CapturePhase)
	*p = x
	return p
}

func (x CapturePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapturePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_monarch_proto_enumTypes[2].Descriptor()
}

func (CapturePhase) Type() protoreflect.EnumType {
	return &file_monarch_proto_enumTypes[2]
}

func (x CapturePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapturePhase.Descriptor instead.
func (CapturePhase) EnumDescriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{2}
}

// Mode mirrors ShadowTest.spec.mode.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_RECORD      Mode = 1
	Mode_MODE_REPLAY      Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_RECORD",
		2: "MODE_REPLAY",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_RECORD":      1,
		"MODE_REPLAY":      2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_monarch_proto_enumTypes[3].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_monarch_proto_enumTypes[3]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{3}
}

// StatusRequest selects which ShadowTests to stream. Leaving both fields empty
// watches every ShadowTest in the cluster.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestName      string                 `protobuf:"bytes,1,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_monarch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monarch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *StatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ComponentStatus reports per-component readiness for the topology graph.
type ComponentStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IgrisReady       bool                   `protobuf:"varint,1,opt,name=igris_ready,json=igrisReady,proto3" json:"igris_ready,omitempty"`
	ShopReady        bool                   `protobuf:"varint,2,opt,name=shop_ready,json=shopReady,proto3" json:"shop_ready,omitempty"`
	BeruReady        bool                   `protobuf:"varint,3,opt,name=beru_ready,json=beruReady,proto3" json:"beru_ready,omitempty"`
	KaiselRuleActive bool                   `protobuf:"varint,4,opt,name=kaisel_rule_active,json=kaiselRuleActive,proto3" json:"kaisel_rule_active,omitempty"`
	AmqpBound        bool                   `protobuf:"varint,5,opt,name=amqp_bound,json=amqpBound,proto3" json:"amqp_bound,omitempty"`
	// Keyed by the role names in roles.go: control-a, control-b, candidate.
	// Empty in record mode, where no shadow roles are provisioned.
	ShadowRolesReady map[string]bool `protobuf:"bytes,6,rep,name=shadow_roles_ready,json=shadowRolesReady,proto3" json:"shadow_roles_ready,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TargetDeployment string          `protobuf:"bytes,7,opt,name=target_deployment,json=targetDeployment,proto3" json:"target_deployment,omitempty"`
	// Resolved ShadowTest.spec.inputs[].driver values (e.g. http_request,
	// rabbitmq_message). Tusk gates topology nodes from this list.
	IngressDrivers []string `protobuf:"bytes,8,rep,name=ingress_drivers,json=ingressDrivers,proto3" json:"ingress_drivers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_monarch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_monarch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentStatus) GetIgrisReady() bool {
	if x != nil {
		return x.IgrisReady
	}
	return false
}

func (x *ComponentStatus) GetShopReady() bool {
	if x != nil {
		return x.ShopReady
	}
	return false
}

func (x *ComponentStatus) GetBeruReady() bool {
	if x != nil {
		return x.BeruReady
	}
	return false
}

func (x *ComponentStatus) GetKaiselRuleActive() bool {
	if x != nil {
		return x.KaiselRuleActive
	}
	return false
}

func (x *ComponentStatus) GetAmqpBound() bool {
	if x != nil {
		return x.AmqpBound
	}
	return false
}

func (x *ComponentStatus) GetShadowRolesReady() map[string]bool {
	if x != nil {
		return x.ShadowRolesReady
	}
	return nil
}

func (x *ComponentStatus) GetTargetDeployment() string {
	if x != nil {
		return x.TargetDeployment
	}
	return ""
}

func (x *ComponentStatus) GetIngressDrivers() []string {
	if x != nil {
		return x.IngressDrivers
	}
	return nil
}

type ShadowTestStatusUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TestName         string                 `protobuf:"bytes,1,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase            Phase                  `protobuf:"varint,3,opt,name=phase,proto3,enum=monarch.v1.Phase" json:"phase,omitempty"`
	BootStep         BootStep               `protobuf:"varint,4,opt,name=boot_step,json=bootStep,proto3,enum=monarch.v1.BootStep" json:"boot_step,omitempty"`
	CurrentSessionId string                 `protobuf:"bytes,5,opt,name=current_session_id,json=currentSessionId,proto3" json:"current_session_id,omitempty"`
	ReplayState      string                 `protobuf:"bytes,6,opt,name=replay_state,json=replayState,proto3" json:"replay_state,omitempty"`
	Components       *ComponentStatus       `protobuf:"bytes,7,opt,name=components,proto3" json:"components,omitempty"`
	Mode             Mode                   `protobuf:"varint,8,opt,name=mode,proto3,enum=monarch.v1.Mode" json:"mode,omitempty"`
	Message          string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	KaiselPhase      CapturePhase           `protobuf:"varint,10,opt,name=kaisel_phase,json=kaiselPhase,proto3,enum=monarch.v1.CapturePhase" json:"kaisel_phase,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShadowTestStatusUpdate) Reset() {
	*x = ShadowTestStatusUpdate{}
	mi := &file_monarch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowTestStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowTestStatusUpdate) ProtoMessage() {}

func (x *ShadowTestStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_monarch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowTestStatusUpdate.ProtoReflect.Descriptor instead.
func (*ShadowTestStatusUpdate) Descriptor() ([]byte, []int) {
	return file_monarch_proto_rawDescGZIP(), []int{2}
}

func (x *ShadowTestStatusUpdate) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *ShadowTestStatusUpdate) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ShadowTestStatusUpdate) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *ShadowTestStatusUpdate) GetBootStep() BootStep {
	if x != nil {
		return x.BootStep
	}
	return BootStep_BOOT_STEP_UNSPECIFIED
}

func (x *ShadowTestStatusUpdate) GetCurrentSessionId() string {
	if x != nil {
		return x.CurrentSessionId
	}
	return ""
}

func (x *ShadowTestStatusUpdate) GetReplayState() string {
	if x != nil {
		return x.ReplayState
	}
	return ""
}

func (x *ShadowTestStatusUpdate) GetComponents() *ComponentStatus {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ShadowTestStatusUpdate) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *ShadowTestStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShadowTestStatusUpdate) GetKaiselPhase() CapturePhase {
	if x != nil {
		return x.KaiselPhase
	}
	return CapturePhase_CAPTURE_PHASE_UNSPECIFIED
}

var File_monarch_proto protoreflect.FileDescriptor

const file_monarch_proto_rawDesc = "" +
	"\n" +
	"\rmonarch.proto\x12\n" +
	"monarch.v1\"J\n" +
	"\rStatusRequest\x12\x1b\n" +
	"\ttest_name\x18\x01 \x01(\tR\btestName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xb9\x03\n" +
	"\x0fComponentStatus\x12\x1f\n" +
	"\vigris_ready\x18\x01 \x01(\bR\n" +
	"igrisReady\x12\x1d\n" +
	"\n" +
	"shop_ready\x18\x02 \x01(\bR\tshopReady\x12\x1d\n" +
	"\n" +
	"beru_ready\x18\x03 \x01(\bR\tberuReady\x12,\n" +
	"\x12kaisel_rule_active\x18\x04 \x01(\bR\x10kaiselRuleActive\x12\x1d\n" +
	"\n" +
	"amqp_bound\x18\x05 \x01(\bR\tamqpBound\x12_\n" +
	"\x12shadow_roles_ready\x18\x06 \x03(\v21.monarch.v1.ComponentStatus.ShadowRolesReadyEntryR\x10shadowRolesReady\x12+\n" +
	"\x11target_deployment\x18\a \x01(\tR\x10targetDeployment\x12'\n" +
	"\x0fingress_drivers\x18\b \x03(\tR\x0eingressDrivers\x1aC\n" +
	"\x15ShadowRolesReadyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xba\x03\n" +
	"\x16ShadowTestStatusUpdate\x12\x1b\n" +
	"\ttest_name\x18\x01 \x01(\tR\btestName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12'\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x11.monarch.v1.PhaseR\x05phase\x121\n" +
	"\tboot_step\x18\x04 \x01(\x0e2\x14.monarch.v1.BootStepR\bbootStep\x12,\n" +
	"\x12current_session_id\x18\x05 \x01(\tR\x10currentSessionId\x12!\n" +
	"\freplay_state\x18\x06 \x01(\tR\vreplayState\x12;\n" +
	"\n" +
	"components\x18\a \x01(\v2\x1b.monarch.v1.ComponentStatusR\n" +
	"components\x12$\n" +
	"\x04mode\x18\b \x01(\x0e2\x10.monarch.v1.ModeR\x04mode\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12;\n" +
	"\fkaisel_phase\x18\n" +
	" \x01(\x0e2\x18.monarch.v1.CapturePhaseR\vkaiselPhase*\x7f\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PHASE_PROGRESSING\x10\x01\x12\x0f\n" +
	"\vPHASE_READY\x10\x02\x12\x10\n" +
	"\fPHASE_FAILED\x10\x03\x12\x12\n" +
	"\x0ePHASE_DELETING\x10\x04\x12\x11\n" +
	"\rPHASE_DELETED\x10\x05*\xf7\x01\n" +
	"\bBootStep\x12\x19\n" +
	"\x15BOOT_STEP_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBOOT_STEP_VALIDATING_INPUTS\x10\x01\x12 \n" +
	"\x1cBOOT_STEP_PROVISIONING_SINKS\x10\x02\x12#\n" +
	"\x1fBOOT_STEP_ACTIVATING_EGRESS_TAP\x10\x03\x12\x1a\n" +
	"\x16BOOT_STEP_BINDING_AMQP\x10\x04\x12!\n" +
	"\x1dBOOT_STEP_PROVISIONING_SHADOW\x10\x05\x12\x13\n" +
	"\x0fBOOT_STEP_READY\x10\x06\x12\x14\n" +
	"\x10BOOT_STEP_FAILED\x10\a*~\n" +
	"\fCapturePhase\x12\x1d\n" +
	"\x19CAPTURE_PHASE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CAPTURE_PHASE_READY\x10\x01\x12\x1a\n" +
	"\x16CAPTURE_PHASE_DEGRADED\x10\x02\x12\x1a\n" +
	"\x16CAPTURE_PHASE_DISABLED\x10\x03*>\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_RECORD\x10\x01\x12\x0f\n" +
	"\vMODE_REPLAY\x10\x022p\n" +
	"\x14MonarchStatusService\x12X\n" +
	"\x15WatchShadowTestStatus\x12\x19.monarch.v1.StatusRequest\x1a\".monarch.v1.ShadowTestStatusUpdate0\x01B,Z*github.com/shadow-diff/monarchpb;monarchpbb\x06proto3"

var (
	file_monarch_proto_rawDescOnce sync.Once
	file_monarch_proto_rawDescData []byte
)

func file_monarch_proto_rawDescGZIP() []byte {
	file_monarch_proto_rawDescOnce.Do(func() {
		file_monarch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monarch_proto_rawDesc), len(file_monarch_proto_rawDesc)))
	})
	return file_monarch_proto_rawDescData
}

var file_monarch_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_monarch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_monarch_proto_goTypes = []any{
	(Phase)(0),                     // 0: monarch.v1.Phase
	(BootStep)(0),                  // 1: monarch.v1.BootStep
	(CapturePhase)(0),              // 2: monarch.v1.CapturePhase
	(Mode)(0),                      // 3: monarch.v1.Mode
	(*StatusRequest)(nil),          // 4: monarch.v1.StatusRequest
	(*ComponentStatus)(nil),        // 5: monarch.v1.ComponentStatus
	(*ShadowTestStatusUpdate)(nil), // 6: monarch.v1.ShadowTestStatusUpdate
	nil,                            // 7: monarch.v1.ComponentStatus.ShadowRolesReadyEntry
}
var file_monarch_proto_depIdxs = []int32{
	7, // 0: monarch.v1.ComponentStatus.shadow_roles_ready:type_name -> monarch.v1.ComponentStatus.ShadowRolesReadyEntry
	0, // 1: monarch.v1.ShadowTestStatusUpdate.phase:type_name -> monarch.v1.Phase
	1, // 2: monarch.v1.ShadowTestStatusUpdate.boot_step:type_name -> monarch.v1.BootStep
	5, // 3: monarch.v1.ShadowTestStatusUpdate.components:type_name -> monarch.v1.ComponentStatus
	3, // 4: monarch.v1.ShadowTestStatusUpdate.mode:type_name -> monarch.v1.Mode
	2, // 5: monarch.v1.ShadowTestStatusUpdate.kaisel_phase:type_name -> monarch.v1.CapturePhase
	4, // 6: monarch.v1.MonarchStatusService.WatchShadowTestStatus:input_type -> monarch.v1.StatusRequest
	6, // 7: monarch.v1.MonarchStatusService.WatchShadowTestStatus:output_type -> monarch.v1.ShadowTestStatusUpdate
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_monarch_proto_init() }
func file_monarch_proto_init() {
	if File_monarch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monarch_proto_rawDesc), len(file_monarch_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monarch_proto_goTypes,
		DependencyIndexes: file_monarch_proto_depIdxs,
		EnumInfos:         file_monarch_proto_enumTypes,
		MessageInfos:      file_monarch_proto_msgTypes,
	}.Build()
	File_monarch_proto = out.File
	file_monarch_proto_goTypes = nil
	file_monarch_proto_depIdxs = nil
}
