// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.6.1
// source: monarch.proto

package monarchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonarchStatusService_WatchShadowTestStatus_FullMethodName = "/monarch.v1.MonarchStatusService/WatchShadowTestStatus"
)

// MonarchStatusServiceClient is the client API for MonarchStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonarchStatusServiceClient interface {
	// WatchShadowTestStatus sends one update per matching ShadowTest on connect
	// (a snapshot of current state), then streams every subsequent change.
	WatchShadowTestStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShadowTestStatusUpdate], error)
}

type monarchStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonarchStatusServiceClient(cc grpc.ClientConnInterface) MonarchStatusServiceClient {
	return &monarchStatusServiceClient{cc}
}

func (c *monarchStatusServiceClient) WatchShadowTestStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShadowTestStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonarchStatusService_ServiceDesc.Streams[0], MonarchStatusService_WatchShadowTestStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, ShadowTestStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonarchStatusService_WatchShadowTestStatusClient = grpc.ServerStreamingClient[ShadowTestStatusUpdate]

// MonarchStatusServiceServer is the server API for MonarchStatusService service.
// All implementations must embed UnimplementedMonarchStatusServiceServer
// for forward compatibility.
type MonarchStatusServiceServer interface {
	// WatchShadowTestStatus sends one update per matching ShadowTest on connect
	// (a snapshot of current state), then streams every subsequent change.
	WatchShadowTestStatus(*StatusRequest, grpc.ServerStreamingServer[ShadowTestStatusUpdate]) error
	mustEmbedUnimplementedMonarchStatusServiceServer()
}

// UnimplementedMonarchStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonarchStatusServiceServer struct{}

func (UnimplementedMonarchStatusServiceServer) WatchShadowTestStatus(*StatusRequest, grpc.ServerStreamingServer[ShadowTestStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchShadowTestStatus not implemented")
}
func (UnimplementedMonarchStatusServiceServer) mustEmbedUnimplementedMonarchStatusServiceServer() {}
func (UnimplementedMonarchStatusServiceServer) testEmbeddedByValue()                              {}

// UnsafeMonarchStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonarchStatusServiceServer will
// result in compilation errors.
type UnsafeMonarchStatusServiceServer interface {
	mustEmbedUnimplementedMonarchStatusServiceServer()
}

func RegisterMonarchStatusServiceServer(s grpc.ServiceRegistrar, srv MonarchStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedMonarchStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonarchStatusService_ServiceDesc, srv)
}

func _MonarchStatusService_WatchShadowTestStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonarchStatusServiceServer).WatchShadowTestStatus(m, &grpc.GenericServerStream[StatusRequest, ShadowTestStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonarchStatusService_WatchShadowTestStatusServer = grpc.ServerStreamingServer[ShadowTestStatusUpdate]

// MonarchStatusService_ServiceDesc is the grpc.ServiceDesc for MonarchStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonarchStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monarch.v1.MonarchStatusService",
	HandlerType: (*MonarchStatusServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchShadowTestStatus",
			Handler:       _MonarchStatusService_WatchShadowTestStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monarch.proto",
}
