//go:build !ignore_autogenerated

/*
Copyright 2026 Shadow-Diff.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQPInputSpec) DeepCopyInto(out *AMQPInputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQPInputSpec.
func (in *AMQPInputSpec) DeepCopy() *AMQPInputSpec {
	if in == nil {
		return nil
	}
	out := new(AMQPInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencySpec) DeepCopyInto(out *DependencySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencySpec.
func (in *DependencySpec) DeepCopy() *DependencySpec {
	if in == nil {
		return nil
	}
	out := new(DependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRelayRabbitMQSpec) DeepCopyInto(out *EgressRelayRabbitMQSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRelayRabbitMQSpec.
func (in *EgressRelayRabbitMQSpec) DeepCopy() *EgressRelayRabbitMQSpec {
	if in == nil {
		return nil
	}
	out := new(EgressRelayRabbitMQSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgrisRabbitMQSpec) DeepCopyInto(out *IgrisRabbitMQSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgrisRabbitMQSpec.
func (in *IgrisRabbitMQSpec) DeepCopy() *IgrisRabbitMQSpec {
	if in == nil {
		return nil
	}
	out := new(IgrisRabbitMQSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgrisSpec) DeepCopyInto(out *IgrisSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgrisSpec.
func (in *IgrisSpec) DeepCopy() *IgrisSpec {
	if in == nil {
		return nil
	}
	out := new(IgrisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputSpec) DeepCopyInto(out *InputSpec) {
	*out = *in
	if in.AMQP != nil {
		in, out := &in.AMQP, &out.AMQP
		*out = new(AMQPInputSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputSpec.
func (in *InputSpec) DeepCopy() *InputSpec {
	if in == nil {
		return nil
	}
	out := new(InputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelInjectionSpec) DeepCopyInto(out *OtelInjectionSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelInjectionSpec.
func (in *OtelInjectionSpec) DeepCopy() *OtelInjectionSpec {
	if in == nil {
		return nil
	}
	out := new(OtelInjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PixieStreamRule) DeepCopyInto(out *PixieStreamRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PixieStreamRule.
func (in *PixieStreamRule) DeepCopy() *PixieStreamRule {
	if in == nil {
		return nil
	}
	out := new(PixieStreamRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PixieStreamRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PixieStreamRuleList) DeepCopyInto(out *PixieStreamRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PixieStreamRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PixieStreamRuleList.
func (in *PixieStreamRuleList) DeepCopy() *PixieStreamRuleList {
	if in == nil {
		return nil
	}
	out := new(PixieStreamRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PixieStreamRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PixieStreamRuleSpec) DeepCopyInto(out *PixieStreamRuleSpec) {
	*out = *in
	if in.TargetLabels != nil {
		in, out := &in.TargetLabels, &out.TargetLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TargetPorts != nil {
		in, out := &in.TargetPorts, &out.TargetPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.RecordAndReplayHosts != nil {
		in, out := &in.RecordAndReplayHosts, &out.RecordAndReplayHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludePaths != nil {
		in, out := &in.ExcludePaths, &out.ExcludePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PixieStreamRuleSpec.
func (in *PixieStreamRuleSpec) DeepCopy() *PixieStreamRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PixieStreamRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PixieStreamRuleStatus) DeepCopyInto(out *PixieStreamRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PixieStreamRuleStatus.
func (in *PixieStreamRuleStatus) DeepCopy() *PixieStreamRuleStatus {
	if in == nil {
		return nil
	}
	out := new(PixieStreamRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordAndReplayHostSpec) DeepCopyInto(out *RecordAndReplayHostSpec) {
	*out = *in
	if in.IgnoreRequestPaths != nil {
		in, out := &in.IgnoreRequestPaths, &out.IgnoreRequestPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordAndReplayHostSpec.
func (in *RecordAndReplayHostSpec) DeepCopy() *RecordAndReplayHostSpec {
	if in == nil {
		return nil
	}
	out := new(RecordAndReplayHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecorderSpec) DeepCopyInto(out *RecorderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecorderSpec.
func (in *RecorderSpec) DeepCopy() *RecorderSpec {
	if in == nil {
		return nil
	}
	out := new(RecorderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTest) DeepCopyInto(out *ShadowTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTest.
func (in *ShadowTest) DeepCopy() *ShadowTest {
	if in == nil {
		return nil
	}
	out := new(ShadowTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTestList) DeepCopyInto(out *ShadowTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShadowTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTestList.
func (in *ShadowTestList) DeepCopy() *ShadowTestList {
	if in == nil {
		return nil
	}
	out := new(ShadowTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTestSpec) DeepCopyInto(out *ShadowTestSpec) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]InputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Igris != nil {
		in, out := &in.Igris, &out.Igris
		*out = new(IgrisSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IgrisRabbitMQ != nil {
		in, out := &in.IgrisRabbitMQ, &out.IgrisRabbitMQ
		*out = new(IgrisRabbitMQSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EgressRelayRabbitMQ != nil {
		in, out := &in.EgressRelayRabbitMQ, &out.EgressRelayRabbitMQ
		*out = new(EgressRelayRabbitMQSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Siphon != nil {
		in, out := &in.Siphon, &out.Siphon
		*out = new(SiphonSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Recorder != nil {
		in, out := &in.Recorder, &out.Recorder
		*out = new(RecorderSpec)
		**out = **in
	}
	if in.RecordAndReplay != nil {
		in, out := &in.RecordAndReplay, &out.RecordAndReplay
		*out = make([]RecordAndReplayHostSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencySpec, len(*in))
		copy(*out, *in)
	}
	if in.OtelInjection != nil {
		in, out := &in.OtelInjection, &out.OtelInjection
		*out = new(OtelInjectionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTestSpec.
func (in *ShadowTestSpec) DeepCopy() *ShadowTestSpec {
	if in == nil {
		return nil
	}
	out := new(ShadowTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTestStatus) DeepCopyInto(out *ShadowTestStatus) {
	*out = *in
	if in.CaptureTargets != nil {
		in, out := &in.CaptureTargets, &out.CaptureTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTestStatus.
func (in *ShadowTestStatus) DeepCopy() *ShadowTestStatus {
	if in == nil {
		return nil
	}
	out := new(ShadowTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiphonSpec) DeepCopyInto(out *SiphonSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludePaths != nil {
		in, out := &in.ExcludePaths, &out.ExcludePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiphonSpec.
func (in *SiphonSpec) DeepCopy() *SiphonSpec {
	if in == nil {
		return nil
	}
	out := new(SiphonSpec)
	in.DeepCopyInto(out)
	return out
}
