//go:build !ignore_autogenerated

/*
Copyright 2026 Shadow-Diff.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQPInputSpec) DeepCopyInto(out *AMQPInputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQPInputSpec.
func (in *AMQPInputSpec) DeepCopy() *AMQPInputSpec {
	if in == nil {
		return nil
	}
	out := new(AMQPInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeruSpec) DeepCopyInto(out *BeruSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeruSpec.
func (in *BeruSpec) DeepCopy() *BeruSpec {
	if in == nil {
		return nil
	}
	out := new(BeruSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencySpec) DeepCopyInto(out *DependencySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencySpec.
func (in *DependencySpec) DeepCopy() *DependencySpec {
	if in == nil {
		return nil
	}
	out := new(DependencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRelayRabbitMQSpec) DeepCopyInto(out *EgressRelayRabbitMQSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRelayRabbitMQSpec.
func (in *EgressRelayRabbitMQSpec) DeepCopy() *EgressRelayRabbitMQSpec {
	if in == nil {
		return nil
	}
	out := new(EgressRelayRabbitMQSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgrisRabbitMQSpec) DeepCopyInto(out *IgrisRabbitMQSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgrisRabbitMQSpec.
func (in *IgrisRabbitMQSpec) DeepCopy() *IgrisRabbitMQSpec {
	if in == nil {
		return nil
	}
	out := new(IgrisRabbitMQSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgrisSpec) DeepCopyInto(out *IgrisSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgrisSpec.
func (in *IgrisSpec) DeepCopy() *IgrisSpec {
	if in == nil {
		return nil
	}
	out := new(IgrisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputSpec) DeepCopyInto(out *InputSpec) {
	*out = *in
	if in.AMQP != nil {
		in, out := &in.AMQP, &out.AMQP
		*out = new(AMQPInputSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputSpec.
func (in *InputSpec) DeepCopy() *InputSpec {
	if in == nil {
		return nil
	}
	out := new(InputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiselRule) DeepCopyInto(out *KaiselRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiselRule.
func (in *KaiselRule) DeepCopy() *KaiselRule {
	if in == nil {
		return nil
	}
	out := new(KaiselRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiselRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiselRuleList) DeepCopyInto(out *KaiselRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KaiselRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiselRuleList.
func (in *KaiselRuleList) DeepCopy() *KaiselRuleList {
	if in == nil {
		return nil
	}
	out := new(KaiselRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiselRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiselRuleSpec) DeepCopyInto(out *KaiselRuleSpec) {
	*out = *in
	if in.TargetIPs != nil {
		in, out := &in.TargetIPs, &out.TargetIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TargetPorts != nil {
		in, out := &in.TargetPorts, &out.TargetPorts
		*out = make([]uint16, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiselRuleSpec.
func (in *KaiselRuleSpec) DeepCopy() *KaiselRuleSpec {
	if in == nil {
		return nil
	}
	out := new(KaiselRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiselRuleStatus) DeepCopyInto(out *KaiselRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiselRuleStatus.
func (in *KaiselRuleStatus) DeepCopy() *KaiselRuleStatus {
	if in == nil {
		return nil
	}
	out := new(KaiselRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowSoldierSpec) DeepCopyInto(out *ShadowSoldierSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowSoldierSpec.
func (in *ShadowSoldierSpec) DeepCopy() *ShadowSoldierSpec {
	if in == nil {
		return nil
	}
	out := new(ShadowSoldierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTest) DeepCopyInto(out *ShadowTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTest.
func (in *ShadowTest) DeepCopy() *ShadowTest {
	if in == nil {
		return nil
	}
	out := new(ShadowTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTestList) DeepCopyInto(out *ShadowTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShadowTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTestList.
func (in *ShadowTestList) DeepCopy() *ShadowTestList {
	if in == nil {
		return nil
	}
	out := new(ShadowTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTestSpec) DeepCopyInto(out *ShadowTestSpec) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]InputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Igris != nil {
		in, out := &in.Igris, &out.Igris
		*out = new(IgrisSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IgrisRabbitMQ != nil {
		in, out := &in.IgrisRabbitMQ, &out.IgrisRabbitMQ
		*out = new(IgrisRabbitMQSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EgressRelayRabbitMQ != nil {
		in, out := &in.EgressRelayRabbitMQ, &out.EgressRelayRabbitMQ
		*out = new(EgressRelayRabbitMQSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Beru != nil {
		in, out := &in.Beru, &out.Beru
		*out = new(BeruSpec)
		**out = **in
	}
	if in.Shop != nil {
		in, out := &in.Shop, &out.Shop
		*out = new(ShopSpec)
		**out = **in
	}
	if in.ShadowSoldier != nil {
		in, out := &in.ShadowSoldier, &out.ShadowSoldier
		*out = new(ShadowSoldierSpec)
		**out = **in
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencySpec, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTestSpec.
func (in *ShadowTestSpec) DeepCopy() *ShadowTestSpec {
	if in == nil {
		return nil
	}
	out := new(ShadowTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowTestStatus) DeepCopyInto(out *ShadowTestStatus) {
	*out = *in
	if in.CaptureTargets != nil {
		in, out := &in.CaptureTargets, &out.CaptureTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowTestStatus.
func (in *ShadowTestStatus) DeepCopy() *ShadowTestStatus {
	if in == nil {
		return nil
	}
	out := new(ShadowTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShopSpec) DeepCopyInto(out *ShopSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShopSpec.
func (in *ShopSpec) DeepCopy() *ShopSpec {
	if in == nil {
		return nil
	}
	out := new(ShopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
