---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - engine.shadow-diff.io
  resources:
  - pixiestreamrules
  - shadowtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - engine.shadow-diff.io
  resources:
  - pixiestreamrules/finalizers
  - shadowtests/finalizers
  verbs:
  - update
- apiGroups:
  - engine.shadow-diff.io
  resources:
  - pixiestreamrules/status
  - shadowtests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opentelemetry.io
  resources:
  - instrumentations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
