// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: traffic.proto

package beruv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_INGRESS               Direction = 1
	Direction_EGRESS                Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "INGRESS",
		2: "EGRESS",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"INGRESS":               1,
		"EGRESS":                2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_traffic_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_traffic_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_traffic_proto_rawDescGZIP(), []int{0}
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payload) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Payload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type TrafficReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=beru.v1.Direction" json:"direction,omitempty"`
	Payload       *Payload               `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficReport) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TrafficReport) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TrafficReport) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *TrafficReport) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReportTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *TrafficReport         `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTrafficRequest) Reset() {
	*x = ReportTrafficRequest{}
	mi := &file_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTrafficRequest) ProtoMessage() {}

func (x *ReportTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTrafficRequest.ProtoReflect.Descriptor instead.
func (*ReportTrafficRequest) Descriptor() ([]byte, []int) {
	return file_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *ReportTrafficRequest) GetReport() *TrafficReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type ReportTrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTrafficResponse) Reset() {
	*x = ReportTrafficResponse{}
	mi := &file_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTrafficResponse) ProtoMessage() {}

func (x *ReportTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTrafficResponse.ProtoReflect.Descriptor instead.
func (*ReportTrafficResponse) Descriptor() ([]byte, []int) {
	return file_traffic_proto_rawDescGZIP(), []int{3}
}

var File_traffic_proto protoreflect.FileDescriptor

const file_traffic_proto_rawDesc = "" +
	"\n" +
	"\rtraffic.proto\x12\aberu.v1\"\xb9\x01\n" +
	"\aPayload\x12:\n" +
	"\bmetadata\x18\x01 \x03(\v2\x1e.beru.v1.Payload.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\rTrafficReport\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x120\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x12.beru.v1.DirectionR\tdirection\x12*\n" +
	"\apayload\x18\x04 \x01(\v2\x10.beru.v1.PayloadR\apayload\"F\n" +
	"\x14ReportTrafficRequest\x12.\n" +
	"\x06report\x18\x01 \x01(\v2\x16.beru.v1.TrafficReportR\x06report\"\x17\n" +
	"\x15ReportTrafficResponse*?\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aINGRESS\x10\x01\x12\n" +
	"\n" +
	"\x06EGRESS\x10\x022a\n" +
	"\x0fTrafficReporter\x12N\n" +
	"\rReportTraffic\x12\x1d.beru.v1.ReportTrafficRequest\x1a\x1e.beru.v1.ReportTrafficResponseB4Z2github.com/shadow-diff/beru/pkg/api/beru/v1;beruv1b\x06proto3"

var (
	file_traffic_proto_rawDescOnce sync.Once
	file_traffic_proto_rawDescData []byte
)

func file_traffic_proto_rawDescGZIP() []byte {
	file_traffic_proto_rawDescOnce.Do(func() {
		file_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_traffic_proto_rawDesc), len(file_traffic_proto_rawDesc)))
	})
	return file_traffic_proto_rawDescData
}

var file_traffic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_traffic_proto_goTypes = []any{
	(Direction)(0),                // 0: beru.v1.Direction
	(*Payload)(nil),               // 1: beru.v1.Payload
	(*TrafficReport)(nil),         // 2: beru.v1.TrafficReport
	(*ReportTrafficRequest)(nil),  // 3: beru.v1.ReportTrafficRequest
	(*ReportTrafficResponse)(nil), // 4: beru.v1.ReportTrafficResponse
	nil,                           // 5: beru.v1.Payload.MetadataEntry
}
var file_traffic_proto_depIdxs = []int32{
	5, // 0: beru.v1.Payload.metadata:type_name -> beru.v1.Payload.MetadataEntry
	0, // 1: beru.v1.TrafficReport.direction:type_name -> beru.v1.Direction
	1, // 2: beru.v1.TrafficReport.payload:type_name -> beru.v1.Payload
	2, // 3: beru.v1.ReportTrafficRequest.report:type_name -> beru.v1.TrafficReport
	3, // 4: beru.v1.TrafficReporter.ReportTraffic:input_type -> beru.v1.ReportTrafficRequest
	4, // 5: beru.v1.TrafficReporter.ReportTraffic:output_type -> beru.v1.ReportTrafficResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_traffic_proto_init() }
func file_traffic_proto_init() {
	if File_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_traffic_proto_rawDesc), len(file_traffic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_traffic_proto_goTypes,
		DependencyIndexes: file_traffic_proto_depIdxs,
		EnumInfos:         file_traffic_proto_enumTypes,
		MessageInfos:      file_traffic_proto_msgTypes,
	}.Build()
	File_traffic_proto = out.File
	file_traffic_proto_goTypes = nil
	file_traffic_proto_depIdxs = nil
}
