apiVersion: engine.shadow-diff.io/v1alpha1
kind: ShadowTest
metadata:
  labels:
    app.kubernetes.io/name: monarch
    app.kubernetes.io/managed-by: kustomize
  name: shadowtest-sample
  namespace: default
spec:
  targetDeployment: my-prod-app
  targetNamespace: default
  oldImage: ghcr.io/org/app:v1
  newImage: ghcr.io/org/app:v2
  servicePort: 8080
  applicationPort: 8081
  beruGRPCAddress: beru.beru-system.svc.cluster.local:50051
