# HTTP ingress (igris-http) + Mongo OTLP + RabbitMQ egress (Firehose) OTel E2E fixtures.
apiVersion: engine.shadow-diff.io/v1alpha1
kind: ShadowTest
metadata:
  name: http-otel-rmq-nodejs-shadow
  namespace: default
spec:
  targetDeployment: http-rmq-nodejs-prod

  oldImage: http-rmq-test-app:dev
  newImage: http-rmq-test-app:dev

  servicePort: 8888
  applicationPort: 8080

  inputs:
    - port: 8888
      driver: http_request

  dependencies:
    - name: rabbitmq
      type: rabbitmq
      envVarInjection: AMQP_URL
    - name: mongodb
      type: mongodb
      image: mongo:4.4
      envVarInjection: MONGO_URL
