# This rule is not used by the project monarch itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to engine.shadow-diff.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: monarch
    app.kubernetes.io/managed-by: kustomize
  name: shadowtest-viewer-role
rules:
- apiGroups:
  - engine.shadow-diff.io
  resources:
  - shadowtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - engine.shadow-diff.io
  resources:
  - shadowtests/status
  verbs:
  - get
