// export-ts writes the shadowspec catalog as a TypeScript module for The System.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/shadow-diff/shadowspec"
)

func main() {
	outPath := filepath.Join("pipeline", "the-system", "src", "lib", "shadowCatalog.ts")
	if len(os.Args) > 1 {
		outPath = os.Args[1]
	}

	raw, err := json.MarshalIndent(shadowspec.GetCatalog(), "", "  ")
	if err != nil {
		fatal(err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by make shadowspec-export; DO NOT EDIT.\n")
	buf.WriteString("// Source: pipeline/pkg/shadowspec\n\n")
	buf.WriteString("export type DependencyKind = {\n")
	buf.WriteString("  type: string\n")
	buf.WriteString("  aliases?: string[]\n")
	buf.WriteString("  defaultImage: string\n")
	buf.WriteString("  defaultPort: number\n")
	buf.WriteString("  suggestedEnvVar: string\n")
	buf.WriteString("  label: string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type InputDriver = {\n")
	buf.WriteString("  driver: string\n")
	buf.WriteString("  label: string\n")
	buf.WriteString("  needsPort: boolean\n")
	buf.WriteString("  needsAmqp: boolean\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type ShadowCatalog = {\n")
	buf.WriteString("  dependencies: DependencyKind[]\n")
	buf.WriteString("  inputs: InputDriver[]\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export const shadowCatalog: ShadowCatalog = ")
	buf.Write(raw)
	buf.WriteString(" as const\n")

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s\n", outPath)
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "export-ts: %v\n", err)
	os.Exit(1)
}
