apiVersion: v1
kind: Service
metadata:
  name: tusk
  namespace: monarch-system
  labels:
    app.kubernetes.io/name: tusk
    app.kubernetes.io/part-of: shadow-diff
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: tusk
