{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "shadow-agent.fullname" . }}
  labels:
    {{- include "shadow-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - engine.shadow-diff.io
    resources:
      - kaiselrules
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shadow-agent.fullname" . }}
  labels:
    {{- include "shadow-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "shadow-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shadow-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
