// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfChunkBuf struct {
	_    structs.HostLayout
	Meta bpfPktMeta
	Data [4096]uint8
}

type bpfPktMeta struct {
	_       structs.HostLayout
	Len     uint32
	OrigLen uint32
	Offset  uint32
	More    uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents        = "events"
	bpfMapFragDrops     = "frag_drops"
	bpfMapScratch       = "scratch"
	bpfMapTargetIps     = "target_ips"
	bpfMapTargetPorts   = "target_ports"
	bpfProgCapture      = "capture"
	bpfVarL2Off         = "l2_off"
	bpfVarPortFilterOn  = "port_filter_on"
	bpfVarUnusedPktMeta = "unused_pkt_meta"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	Capture *ebpf.ProgramSpec `ebpf:"capture"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	FragDrops   *ebpf.MapSpec `ebpf:"frag_drops"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	TargetIps   *ebpf.MapSpec `ebpf:"target_ips"`
	TargetPorts *ebpf.MapSpec `ebpf:"target_ports"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	L2Off         *ebpf.VariableSpec `ebpf:"l2_off"`
	PortFilterOn  *ebpf.VariableSpec `ebpf:"port_filter_on"`
	UnusedPktMeta *ebpf.VariableSpec `ebpf:"unused_pkt_meta"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	FragDrops   *ebpf.Map `ebpf:"frag_drops"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	TargetIps   *ebpf.Map `ebpf:"target_ips"`
	TargetPorts *ebpf.Map `ebpf:"target_ports"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.FragDrops,
		m.Scratch,
		m.TargetIps,
		m.TargetPorts,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	L2Off         *ebpf.Variable `ebpf:"l2_off"`
	PortFilterOn  *ebpf.Variable `ebpf:"port_filter_on"`
	UnusedPktMeta *ebpf.Variable `ebpf:"unused_pkt_meta"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	Capture *ebpf.Program `ebpf:"capture"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.Capture,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
