// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type nogateChunkBuf struct {
	_    structs.HostLayout
	Meta struct {
		_       structs.HostLayout
		Len     uint32
		OrigLen uint32
		Offset  uint32
		More    uint32
	}
	Data [4096]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	nogateMapEvents        = "events"
	nogateMapFragDrops     = "frag_drops"
	nogateMapScratch       = "scratch"
	nogateMapTargetIps     = "target_ips"
	nogateMapTargetPorts   = "target_ports"
	nogateProgCapture      = "capture"
	nogateVarL2Off         = "l2_off"
	nogateVarLoIfindex     = "lo_ifindex"
	nogateVarPortFilterOn  = "port_filter_on"
	nogateVarUnusedPktMeta = "unused_pkt_meta"
)

// loadNogate returns the embedded CollectionSpec for nogate.
func loadNogate() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NogateBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nogate: %w", err)
	}

	return spec, err
}

// loadNogateObjects loads nogate and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nogateObjects
//	*nogatePrograms
//	*nogateMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNogateObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNogate()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nogateSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nogateSpecs struct {
	nogateProgramSpecs
	nogateMapSpecs
	nogateVariableSpecs
}

// nogateProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nogateProgramSpecs struct {
	Capture *ebpf.ProgramSpec `ebpf:"capture"`
}

// nogateMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nogateMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	FragDrops   *ebpf.MapSpec `ebpf:"frag_drops"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	TargetIps   *ebpf.MapSpec `ebpf:"target_ips"`
	TargetPorts *ebpf.MapSpec `ebpf:"target_ports"`
}

// nogateVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nogateVariableSpecs struct {
	L2Off         *ebpf.VariableSpec `ebpf:"l2_off"`
	LoIfindex     *ebpf.VariableSpec `ebpf:"lo_ifindex"`
	PortFilterOn  *ebpf.VariableSpec `ebpf:"port_filter_on"`
	UnusedPktMeta *ebpf.VariableSpec `ebpf:"unused_pkt_meta"`
}

// nogateObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNogateObjects or ebpf.CollectionSpec.LoadAndAssign.
type nogateObjects struct {
	nogatePrograms
	nogateMaps
	nogateVariables
}

func (o *nogateObjects) Close() error {
	return _NogateClose(
		&o.nogatePrograms,
		&o.nogateMaps,
	)
}

// nogateMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNogateObjects or ebpf.CollectionSpec.LoadAndAssign.
type nogateMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	FragDrops   *ebpf.Map `ebpf:"frag_drops"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	TargetIps   *ebpf.Map `ebpf:"target_ips"`
	TargetPorts *ebpf.Map `ebpf:"target_ports"`
}

func (m *nogateMaps) Close() error {
	return _NogateClose(
		m.Events,
		m.FragDrops,
		m.Scratch,
		m.TargetIps,
		m.TargetPorts,
	)
}

// nogateVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNogateObjects or ebpf.CollectionSpec.LoadAndAssign.
type nogateVariables struct {
	L2Off         *ebpf.Variable `ebpf:"l2_off"`
	LoIfindex     *ebpf.Variable `ebpf:"lo_ifindex"`
	PortFilterOn  *ebpf.Variable `ebpf:"port_filter_on"`
	UnusedPktMeta *ebpf.Variable `ebpf:"unused_pkt_meta"`
}

// nogatePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNogateObjects or ebpf.CollectionSpec.LoadAndAssign.
type nogatePrograms struct {
	Capture *ebpf.Program `ebpf:"capture"`
}

func (p *nogatePrograms) Close() error {
	return _NogateClose(
		p.Capture,
	)
}

func _NogateClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nogate_bpfel.o
var _NogateBytes []byte
