// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: traffic.proto

package beruv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficReporter_ReportTraffic_FullMethodName = "/beru.v1.TrafficReporter/ReportTraffic"
)

// TrafficReporterClient is the client API for TrafficReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficReporterClient interface {
	ReportTraffic(ctx context.Context, in *ReportTrafficRequest, opts ...grpc.CallOption) (*ReportTrafficResponse, error)
}

type trafficReporterClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficReporterClient(cc grpc.ClientConnInterface) TrafficReporterClient {
	return &trafficReporterClient{cc}
}

func (c *trafficReporterClient) ReportTraffic(ctx context.Context, in *ReportTrafficRequest, opts ...grpc.CallOption) (*ReportTrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTrafficResponse)
	err := c.cc.Invoke(ctx, TrafficReporter_ReportTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficReporterServer is the server API for TrafficReporter service.
// All implementations must embed UnimplementedTrafficReporterServer
// for forward compatibility.
type TrafficReporterServer interface {
	ReportTraffic(context.Context, *ReportTrafficRequest) (*ReportTrafficResponse, error)
	mustEmbedUnimplementedTrafficReporterServer()
}

// UnimplementedTrafficReporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficReporterServer struct{}

func (UnimplementedTrafficReporterServer) ReportTraffic(context.Context, *ReportTrafficRequest) (*ReportTrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedTrafficReporterServer) mustEmbedUnimplementedTrafficReporterServer() {}
func (UnimplementedTrafficReporterServer) testEmbeddedByValue()                         {}

// UnsafeTrafficReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficReporterServer will
// result in compilation errors.
type UnsafeTrafficReporterServer interface {
	mustEmbedUnimplementedTrafficReporterServer()
}

func RegisterTrafficReporterServer(s grpc.ServiceRegistrar, srv TrafficReporterServer) {
	// If the following call pancis, it indicates UnimplementedTrafficReporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficReporter_ServiceDesc, srv)
}

func _TrafficReporter_ReportTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficReporterServer).ReportTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficReporter_ReportTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficReporterServer).ReportTraffic(ctx, req.(*ReportTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficReporter_ServiceDesc is the grpc.ServiceDesc for TrafficReporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficReporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beru.v1.TrafficReporter",
	HandlerType: (*TrafficReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportTraffic",
			Handler:    _TrafficReporter_ReportTraffic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "traffic.proto",
}
